# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 569ebf1a950b1bf17221db6b680f1eda696308af80378a4702fa1265fb360b294ed852449cb92d532a012efb31ef5e89887bb94641dec0ca2ff6e0750fe70bec

test:
  secret_key_base: a1051636610fec5d6fe9b7bed49093876ab1f98efc5a8ff95e669f3df6c7039e2ea954d11230cce97a1ece7205d09603ba174639c16f02a146d65ffa7636ba53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
